/**
 * Agent Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Context to be used in a ChatAgent endpoint.  Args:     conversation_id (str): The ID of the conversation. **Optional** defaults to ``None``     user_id (str): The ID of the user. **Optional** defaults to ``None``
*/
export class ChatContext {
    'conversationId'?: string | null;
    'userId'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChatContext.attributeTypeMap;
    }

    public constructor() {
    }
}
