/**
 * Agent Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReasoningParams {
    'effort'?: string | null;
    'generateSummary'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "effort",
            "baseName": "effort",
            "type": "string",
            "format": ""
        },
        {
            "name": "generateSummary",
            "baseName": "generate_summary",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReasoningParams.attributeTypeMap;
    }

    public constructor() {
    }
}
