/**
 * Agent Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IncompleteDetails } from '../models/IncompleteDetails';
import { OutputItem } from '../models/OutputItem';
import { ReasoningParams } from '../models/ReasoningParams';
import { ResponseError } from '../models/ResponseError';
import { ResponseUsage } from '../models/ResponseUsage';
import { Tool } from '../models/Tool';
import { ToolChoice } from '../models/ToolChoice';
import { HttpFile } from '../http/http';

/**
* Response object for ResponsesAgent.  Args:     output: List of output items. See examples at         https://mlflow.org/docs/latest/genai/flavors/responses-agent-intro#creating-agent-output.     reasoning: Reasoning parameters     usage: Usage information     custom_outputs (Dict[str, Any]): An optional param to provide arbitrary additional context         from the model. The dictionary values must be JSON-serializable. **Optional**, defaults         to ``None``
*/
export class ResponsesAgentResponse {
    'toolChoice'?: ToolChoice | null;
    'truncation'?: string | null;
    'id'?: string | null;
    'createdAt'?: number | null;
    'error'?: ResponseError | null;
    'incompleteDetails'?: IncompleteDetails | null;
    'instructions'?: string | null;
    'metadata'?: { [key: string]: string; } | null;
    'model'?: string | null;
    'object'?: string;
    'output': Array<OutputItem>;
    'parallelToolCalls'?: boolean | null;
    'temperature'?: number | null;
    'tools'?: Array<Tool> | null;
    'topP'?: number | null;
    'maxOutputTokens'?: number | null;
    'previousResponseId'?: string | null;
    'reasoning'?: ReasoningParams | null;
    'status'?: string | null;
    'text'?:  | null;
    'usage'?: ResponseUsage | null;
    'user'?: string | null;
    'customOutputs'?: { [key: string]: any; } | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "toolChoice",
            "baseName": "tool_choice",
            "type": "ToolChoice",
            "format": ""
        },
        {
            "name": "truncation",
            "baseName": "truncation",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "number",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "ResponseError",
            "format": ""
        },
        {
            "name": "incompleteDetails",
            "baseName": "incomplete_details",
            "type": "IncompleteDetails",
            "format": ""
        },
        {
            "name": "instructions",
            "baseName": "instructions",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        },
        {
            "name": "object",
            "baseName": "object",
            "type": "string",
            "format": ""
        },
        {
            "name": "output",
            "baseName": "output",
            "type": "Array<OutputItem>",
            "format": ""
        },
        {
            "name": "parallelToolCalls",
            "baseName": "parallel_tool_calls",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "number",
            "format": ""
        },
        {
            "name": "tools",
            "baseName": "tools",
            "type": "Array<Tool>",
            "format": ""
        },
        {
            "name": "topP",
            "baseName": "top_p",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxOutputTokens",
            "baseName": "max_output_tokens",
            "type": "number",
            "format": ""
        },
        {
            "name": "previousResponseId",
            "baseName": "previous_response_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "reasoning",
            "baseName": "reasoning",
            "type": "ReasoningParams",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "",
            "format": ""
        },
        {
            "name": "usage",
            "baseName": "usage",
            "type": "ResponseUsage",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": ""
        },
        {
            "name": "customOutputs",
            "baseName": "custom_outputs",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResponsesAgentResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
