/**
 * Agent Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChatContext } from '../models/ChatContext';
import { ReasoningParams } from '../models/ReasoningParams';
import { ResponsesAgentRequestInputInner } from '../models/ResponsesAgentRequestInputInner';
import { Tool } from '../models/Tool';
import { ToolChoice } from '../models/ToolChoice';
import { HttpFile } from '../http/http';

/**
* Request object for ResponsesAgent.  Args:     input: List of simple `role` and `content` messages or output items. See examples at         https://mlflow.org/docs/latest/genai/flavors/responses-agent-intro#testing-out-your-agent         and         https://mlflow.org/docs/latest/genai/flavors/responses-agent-intro#creating-agent-output.     custom_inputs (Dict[str, Any]): An optional param to provide arbitrary additional context         to the model. The dictionary values must be JSON-serializable.         **Optional** defaults to ``None``     context (:py:class:`mlflow.types.agent.ChatContext`): The context to be used in the chat         endpoint. Includes conversation_id and user_id. **Optional** defaults to ``None``
*/
export class ResponsesAgentRequest {
    'toolChoice'?: ToolChoice | null;
    'truncation'?: string | null;
    'maxOutputTokens'?: number | null;
    'metadata'?: { [key: string]: string; } | null;
    'parallelToolCalls'?: boolean | null;
    'tools'?: Array<Tool> | null;
    'reasoning'?: ReasoningParams | null;
    'store'?: boolean | null;
    'stream'?: boolean | null;
    'temperature'?: number | null;
    'text'?:  | null;
    'topP'?: number | null;
    'user'?: string | null;
    'input': Array<ResponsesAgentRequestInputInner>;
    'customInputs'?: { [key: string]: any; } | null;
    'context'?: ChatContext | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "toolChoice",
            "baseName": "tool_choice",
            "type": "ToolChoice",
            "format": ""
        },
        {
            "name": "truncation",
            "baseName": "truncation",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxOutputTokens",
            "baseName": "max_output_tokens",
            "type": "number",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "parallelToolCalls",
            "baseName": "parallel_tool_calls",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "tools",
            "baseName": "tools",
            "type": "Array<Tool>",
            "format": ""
        },
        {
            "name": "reasoning",
            "baseName": "reasoning",
            "type": "ReasoningParams",
            "format": ""
        },
        {
            "name": "store",
            "baseName": "store",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "stream",
            "baseName": "stream",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "temperature",
            "baseName": "temperature",
            "type": "number",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "",
            "format": ""
        },
        {
            "name": "topP",
            "baseName": "top_p",
            "type": "number",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": ""
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "Array<ResponsesAgentRequestInputInner>",
            "format": ""
        },
        {
            "name": "customInputs",
            "baseName": "custom_inputs",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "ChatContext",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResponsesAgentRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
