/**
 * Agent Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InputTokensDetails } from '../models/InputTokensDetails';
import { OutputTokensDetails } from '../models/OutputTokensDetails';
import { HttpFile } from '../http/http';

export class ResponseUsage {
    'inputTokens': number;
    'inputTokensDetails': InputTokensDetails;
    'outputTokens': number;
    'outputTokensDetails': OutputTokensDetails;
    'totalTokens': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "inputTokens",
            "baseName": "input_tokens",
            "type": "number",
            "format": ""
        },
        {
            "name": "inputTokensDetails",
            "baseName": "input_tokens_details",
            "type": "InputTokensDetails",
            "format": ""
        },
        {
            "name": "outputTokens",
            "baseName": "output_tokens",
            "type": "number",
            "format": ""
        },
        {
            "name": "outputTokensDetails",
            "baseName": "output_tokens_details",
            "type": "OutputTokensDetails",
            "format": ""
        },
        {
            "name": "totalTokens",
            "baseName": "total_tokens",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResponseUsage.attributeTypeMap;
    }

    public constructor() {
    }
}
